<a href="https://colab.research.google.com/github/Vinay007-coder/ai-engineering-portfolio/blob/learning-notebooks/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu128
True


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[2,4], [9,10]])
MATRIX

tensor([[ 2,  4],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[1,2,3], [4,5,6]], [[2,3,4], [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[2, 3, 4],
         [5, 6, 7]]])

In [ ]:
TENSOR.shape

torch.Size([2, 2, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR = torch.tensor([[
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]])
TENSOR

tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])

In [ ]:
TENSOR.ndim

4

# Random Tensors

In [ ]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0077, 0.8395, 0.8800, 0.8587],
        [0.0690, 0.1372, 0.2402, 0.3127],
        [0.9106, 0.6690, 0.0860, 0.0428]])

In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7764, 0.6415, 0.6677, 0.4355],
         [0.1922, 0.9027, 0.3579, 0.7288],
         [0.9173, 0.3112, 0.6880, 0.6485]]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes.dtype

torch.float32

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [ ]:
# torch.range() will be deprecated, so use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=1, end=1000, step=50)
one_to_ten

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [ ]:
one_to_ten = torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor Data Types

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1.   Tensors not right datatype
2.   Tensors not right shape
3. Tensors not on the right device



In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting Information

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3211, 0.7755, 0.4381, 0.9086],
        [0.5025, 0.5032, 0.6888, 0.6724],
        [0.2947, 0.1254, 0.2234, 0.6793]])

In [ ]:
# Find details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3211, 0.7755, 0.4381, 0.9086],
        [0.5025, 0.5032, 0.6888, 0.6724],
        [0.2947, 0.1254, 0.2234, 0.6793]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Tensor Indexing & Slicing

In [ ]:
# Creating a 3D tensor
tensor_3d = np.array([
    [ # Page 0
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
    [ # Page 1
        [20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]
    ]
])

In [ ]:
# Tensor Indexing (Grabbing a Single Number)
# Goal: Grab the number 24 from Page 1, Row 1, Column 1
single_number = tensor_3d[1, 1, 1]
print("Indexed Number:", single_number)
# Output: 24

# Goal: Grab the number 12 from Page 0, Row 0, Column 2
another_number = tensor_3d[0, 0, 2]
print("Indexed Number:", another_number)
# Output: 12

Indexed Number: 24
Indexed Number: 12


In [ ]:
# Tensor Slicing (Extracting Sections)

# Slice a single page
# Grab everything on Page 0 (leaving row and column blank means get all of them)
page_0 = tensor_3d[0, :, :]
print("Page 0 Matrix:\n", page_0)
# Output:
# [[10 11 12]
#  [13 14 15]
#  [16 17 18]]


Page 0 Matrix:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
# Slice a specific row across all pages
# Grab Row 0 from BOTH pages
rows_0 = tensor_3d[:, 0, :]
print("Row 0 from all pages:\n", rows_0)
# Output:
# [[10 11 12]
#  [20 21 22]]


Row 0 from all pages:
 [[10 11 12]
 [20 21 22]]


In [ ]:
# Slice a specific sub-grid (The center square)
# From Page 1, grab rows 0 to 2 and columns 0 to 2
# Remember: '0:2' means it grabs index 0 and 1, but stops before 2.
sub_grid = tensor_3d[1, 0:2, 0:2]
print("Sub-grid:\n", sub_grid)
# Output:
# [[20 21]
#  [23 24]]


Sub-grid:
 [[20 21]
 [23 24]]


# Manipulation (Tensor Operations)

Tensor operations include:

*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Mutiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Divide tensor by 2
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
# Subtract by 2
tensor - 2

tensor([-1,  0,  1])

# Matrix Multiplication

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 591 µs, total: 591 µs
Wall time: 491 µs


tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
# Through loop
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.19 ms, sys: 0 ns, total: 1.19 ms
Wall time: 2.75 ms


# **Matrix multiplication**
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:

*   (3, 2) @ (3, 2) won't work
*   (2, 3) @ (3, 2) will work
*   (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

*   (2, 3) @ (3, 2) -> (2, 2)
*   (3, 2) @ (2, 3) -> (3, 3)







# Dealing with tensor shape errors

In [ ]:
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_B = torch.tensor([[2,3], [3,4], [5,6]])
tensor_B

tensor([[2, 3],
        [3, 4],
        [5, 6]])

In [ ]:
# torch.mm(tensor_A, tensor_B) -> Alias for the torch.matmul()
torch.matmul(tensor_A, tensor_B)
# Output: RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[2, 3],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape
# Satisfies our first rule: (3,2) (2,3)

(tensor([[2, 3, 5],
         [3, 4, 6]]),
 torch.Size([2, 3]))

In [ ]:
output = torch.matmul(tensor_A, tensor_B.T)
# We will get a successful output

tensor([[ 8, 11, 17],
        [18, 25, 39],
        [28, 39, 61]])

In [ ]:
output.shape
# Output: torch.Size([3, 3]) -> Satisfies our second rule

torch.Size([3, 3])

# Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensore of float32 datatype.
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

# **Reshaping, stacking, squeezing, and unsqueezing tensors**

*   **Reshaping** - reshapes an input tensor to a defined shape

*   **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

*   **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)

*   **Squeeze** - removes all 1 dimensions from a tensor

*   **Unsqueeze** - add a 1 dimension to a target tensor

*   **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way







In [15]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [14]:
# Let's Add an extra dimension
# x_reshaped = x.reshape(1,7)
# When we tried to put a tensor of size 7 into 9, we got this error:
# RuntimeError: shape '[1, 7]' is invalid for input of size 9
# x_reshaped = x.reshape(2,9)
# We can't reshape this tensor by trying to make it 2 dimensional, because the size will be 2 * 9, which is 18 and that's more than our input size 9
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [16]:
x = torch.arange(1., 11.)
x, x.shape, x.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 1)

In [11]:
#  Add an extra dimension
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]),
 2)

In [22]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

| Code         | What it extracts                                 |
| ------------ | ------------------------------------------------ |
| `z[2, 3]`    | A single number at Row 2, Column 3               |
| `z[1, :]`    | The entire second row                            |
| `z[:, -1]`   | The entire last column                           |
| `z[0:3, :]`  | The first 3 rows                                 |
| `z[:, ::-1]` | Flips the matrix horizontally (reverses columns) |


In [23]:
# Changing z changes x, because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [36]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape, x_stacked.ndim

(tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]),
 torch.Size([10, 4]),
 2)

In [33]:
# Creating two 1D tensors with 3 elements each
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a, b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [34]:
# Vertical Stacking (torch.vstack)
# Stack vertically
v_result = torch.vstack([a, b])

print("Vertical Stack Result:\n", v_result)
print("Resulting Shape:", v_result.shape)

# Output Matrix (2 rows, 3 columns):
# [[1, 2, 3],
#  [4, 5, 6]]
# Shape: torch.Size([2, 3])

Vertical Stack Result:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Resulting Shape: torch.Size([2, 3])


In [35]:
# Horizontal Stacking (torch.hstack)
# Stack horizontally
h_result = torch.hstack([a, b])

print("Horizontal Stack Result:", h_result)
print("Resulting Shape:", h_result.shape)

# Output Vector (1 row with 6 elements):
# [1, 2, 3, 4, 5, 6]
# Shape: torch.Size([6])

Horizontal Stack Result: tensor([1, 2, 3, 4, 5, 6])
Resulting Shape: torch.Size([6])


In [37]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [43]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [44]:
#  torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [53]:
x_original[0,0,0] = 0.9000
x_original[0,0,0], x_permuted[0,0,0]
# Returns a view of the original tensor input with its dimensions permuted.

(tensor(0.9000), tensor(0.9000))

# Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [54]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
# Let's index on our new tensor (dim = 0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [59]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(4)

In [60]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [63]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [64]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [68]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor(9)

In [69]:
#  Index on x to return 9
x[0, 2, 2]

tensor(9)

In [70]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

# PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

*   Data in NumPy -> PyTorch tensor -> torch.from_numpy(ndarray)
*   PyTorch tensor -> NumPy -> torch.Tensor.numpy()



In [71]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor
# They don't share same memory, so nothing will happen to `tensor`

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
# When converting from tensor -> numpy, numpy reflects pytorch's default datatype of float32 unless specified otherwise
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor
# They don't share same memory, so nothing will happen to `numpy_tensor`

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch, here comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [76]:
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0256, 0.9287, 0.4081, 0.8238],
        [0.4789, 0.9656, 0.4722, 0.4338],
        [0.0551, 0.4807, 0.4423, 0.0424]])

Tensor B:
tensor([[0.4804, 0.3324, 0.5344, 0.4610],
        [0.2995, 0.0110, 0.9910, 0.8156],
        [0.7704, 0.4912, 0.6226, 0.0851]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [77]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

# 1. Getting a GPU

1.   Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2.   Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU.
3. Use cloud computing - GCP, AWS, Azure



In [1]:
!nvidia-smi

Mon May 25 11:54:03 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

# 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [4]:
# Create a tensor (default on the cpu)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# 4. Moving tensors back to the CPU

In [6]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [7]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])